import {
  DashboardSummary,
  Job,
  Recruiter,
  Application,
  ApprovalRequest,
  ScoringConfig,
  IntegrationsStatus,
} from "./types";

export const FALLBACK_SUMMARY: DashboardSummary = {
  urgent_opportunities_count: 3,
  recruiter_replies_count: 2,
  followups_due_count: 1,
  approvals_pending_count: 1,
  interviews_this_week_count: 2,
  active_applications_count: 6,
  funnel_bottleneck: "RECRUITER_SCREEN_CONVERSION",
  career_gps_top_action: {
    title: "Apply to Senior Analytics Engineer at Snowflake",
    reason: "100% required skill alignment, verified evidence density of 86%, and compensation within target band ($180k - $210k). Freshly verified active.",
    cta_label: "Review Snowflake Match",
    cta_route: "/jobs",
  },
};

export const FALLBACK_JOBS: any[] = [
  {
    id: "demo-snow-1",
    title: "Senior Analytics Engineer",
    company_name: "Snowflake",
    location: "San Francisco, CA (Remote)",
    source: "GREENHOUSE",
    source_url: "https://boards.greenhouse.io/snowflake/jobs/demo-1",
    status: "VERIFIED",
    verified_status: "ACTIVE",
    priority_score: 89,
    urgency_score: 93,
    actionability: "READY_TO_ACT",
    effort_level: "LOW",
    recommended_action: "APPLY",
    lifecycle_status: "READY_TO_ACT",
    salary_min: 180000,
    salary_max: 210000,
    salary_currency: "USD",
    salary_period: "YEAR",
    remote_status: "REMOTE",
    seniority_level: "SENIOR",
    extracted_required_skills: ["Snowflake", "dbt", "SQL", "Data Modeling", "Python"],
    extracted_preferred_skills: ["Looker", "Airflow", "CI/CD"],
    created_at: new Date(Date.now() - 3600000 * 18).toISOString(),
    arjuna_match_json: {
      match_verdict: "STRONG_MATCH",
      required_coverage_pct: 100,
      preferred_coverage_pct: 67,
      evidence_density_pct: 86,
      seniority_fit_pct: 95,
      matched_required: ["Snowflake", "dbt", "SQL", "Data Modeling", "Python"],
      missing_required: [],
      matched_preferred: ["Looker", "Airflow"],
      missing_preferred: ["CI/CD"],
      reasoning: "Candidate possesses verified ground-truth evidence across all 5 required technical competencies with documented production impact.",
      action_recommendation: "PRIORITIZE_APPLY",
    },
    kubera_comp_json: {
      tier: "STRONG",
      financial_fit_pct: 88,
      salary_fit_pct: 90,
      market_pos_pct: 85,
      remote_val_pct: 100,
      location_val_pct: 90,
      disclosed_salary_present: true,
      converted_min_target: 180000,
      converted_max_target: 210000,
      currency_code: "USD",
      exchange_rate_used: 1.0,
      fx_rate_applied: false,
      reasoning: "Base salary ($180k - $210k) fully meets target policy ($160k min / $185k target) with 100% remote flexibility.",
    },
    chanakya_json: {
      priority_score: 89,
      urgency_score: 93,
      tier: "CRITICAL",
      actionability: "READY_TO_ACT",
      effort_level: "LOW",
      recommended_action: "APPLY",
      lifecycle_status: "READY_TO_ACT",
      why_ranked_here: "CRITICAL tier assigned due to 100% required skill alignment and $180k-$210k compensation fit.",
      positive_factors: [
        "100% required skill coverage backed by candidate evidence",
        "Full remote work alignment",
        "Fresh posting (verified active within 24h)",
      ],
      negative_factors: [],
      execution_notes: "Submit tailored resume highlighting Snowflake cost optimization and dbt data modeling metrics.",
    },
  },
  {
    id: "demo-stripe-2",
    title: "Lead BI Solutions Architect",
    company_name: "Stripe",
    location: "Seattle, WA (Hybrid)",
    source: "LEVER",
    source_url: "https://jobs.lever.co/stripe/demo-2",
    status: "VERIFIED",
    verified_status: "ACTIVE",
    priority_score: 82,
    urgency_score: 84,
    actionability: "NEEDS_RECRUITER_OUTREACH",
    effort_level: "MEDIUM",
    recommended_action: "CONTACT_RECRUITER",
    lifecycle_status: "SHORTLISTED",
    salary_min: 195000,
    salary_max: 235000,
    salary_currency: "USD",
    salary_period: "YEAR",
    remote_status: "HYBRID",
    seniority_level: "LEAD",
    extracted_required_skills: ["SQL", "Looker", "Tableau", "Data Architecture", "Stakeholder Management"],
    extracted_preferred_skills: ["dbt", "Snowflake", "Presto"],
    created_at: new Date(Date.now() - 3600000 * 48).toISOString(),
    arjuna_match_json: {
      match_verdict: "STRONG_MATCH",
      required_coverage_pct: 100,
      preferred_coverage_pct: 100,
      evidence_density_pct: 80,
      seniority_fit_pct: 90,
      matched_required: ["SQL", "Looker", "Tableau", "Data Architecture", "Stakeholder Management"],
      missing_required: [],
      matched_preferred: ["dbt", "Snowflake"],
      missing_preferred: [],
      reasoning: "Strong architectural alignment with documented executive reporting experience.",
      action_recommendation: "RECRUITER_OUTREACH",
    },
    kubera_comp_json: {
      tier: "PREMIUM",
      financial_fit_pct: 94,
      salary_fit_pct: 96,
      market_pos_pct: 92,
      remote_val_pct: 80,
      location_val_pct: 85,
      disclosed_salary_present: true,
      converted_min_target: 195000,
      converted_max_target: 235000,
      currency_code: "USD",
      exchange_rate_used: 1.0,
      fx_rate_applied: false,
      reasoning: "Base compensation ($195k - $235k) in upper 90th percentile for Lead BI roles.",
    },
    chanakya_json: {
      priority_score: 82,
      urgency_score: 84,
      tier: "HIGH",
      actionability: "NEEDS_RECRUITER_OUTREACH",
      effort_level: "MEDIUM",
      recommended_action: "CONTACT_RECRUITER",
      lifecycle_status: "SHORTLISTED",
      why_ranked_here: "HIGH tier assigned due to premium compensation and strong leadership alignment.",
      positive_factors: [
        "100% skill match with extensive enterprise BI leadership background",
        "Compensation in top 90th percentile",
      ],
      negative_factors: ["Hybrid Seattle requirement"],
      execution_notes: "Reach out directly to technical talent lead with architectural portfolio summary.",
    },
  },
  {
    id: "demo-databricks-3",
    title: "Principal Data Platform Engineer",
    company_name: "Databricks",
    location: "San Francisco, CA (Remote)",
    source: "MANUAL",
    status: "VERIFIED",
    verified_status: "ACTIVE",
    priority_score: 76,
    urgency_score: 70,
    actionability: "NEEDS_RESUME",
    effort_level: "MEDIUM",
    recommended_action: "PREPARE_RESUME",
    lifecycle_status: "EVALUATED",
    salary_min: 210000,
    salary_max: 260000,
    salary_currency: "USD",
    salary_period: "YEAR",
    remote_status: "REMOTE",
    seniority_level: "PRINCIPAL",
    extracted_required_skills: ["Spark", "Delta Lake", "Python", "SQL", "Data Lakehouse Architecture"],
    extracted_preferred_skills: ["Kubernetes", "Kafka", "Iceberg"],
    created_at: new Date(Date.now() - 3600000 * 96).toISOString(),
    arjuna_match_json: {
      match_verdict: "MODERATE_MATCH",
      required_coverage_pct: 80,
      preferred_coverage_pct: 33,
      evidence_density_pct: 75,
      seniority_fit_pct: 85,
      matched_required: ["Spark", "Python", "SQL", "Data Lakehouse Architecture"],
      missing_required: ["Delta Lake"],
      matched_preferred: ["Iceberg"],
      missing_preferred: ["Kubernetes", "Kafka"],
      reasoning: "High platform architecture fit; candidate has Iceberg experience that maps closely to Delta Lake requirement.",
      action_recommendation: "TAILOR_RESUME",
    },
    kubera_comp_json: {
      tier: "PREMIUM",
      financial_fit_pct: 96,
      salary_fit_pct: 98,
      market_pos_pct: 95,
      remote_val_pct: 100,
      location_val_pct: 90,
      disclosed_salary_present: true,
      converted_min_target: 210000,
      converted_max_target: 260000,
      currency_code: "USD",
      exchange_rate_used: 1.0,
      fx_rate_applied: false,
      reasoning: "Top-tier principal compensation ($210k - $260k) with full remote flexibility.",
    },
    chanakya_json: {
      priority_score: 76,
      urgency_score: 70,
      tier: "HIGH",
      actionability: "NEEDS_RESUME",
      effort_level: "MEDIUM",
      recommended_action: "PREPARE_RESUME",
      lifecycle_status: "EVALUATED",
      why_ranked_here: "HIGH tier due to elite compensation and lakehouse architecture crossover.",
      positive_factors: [
        "Premium compensation band",
        "Verified lakehouse and query optimization background",
      ],
      negative_factors: ["Missing explicit Delta Lake project in Evidence Bank"],
      execution_notes: "Highlight Apache Iceberg and columnar storage optimization evidence in resume.",
    },
  },
];

export const FALLBACK_EVIDENCE = [
  {
    id: "ev-1",
    competency: "Snowflake Cost & Performance Optimization",
    category: "DATA_WAREHOUSING",
    skill_or_tool: "Snowflake",
    proficiency_level: "EXPERT",
    verified: true,
    employer: "Acme Corp",
    project_title: "Enterprise Warehouse Cost & Concurrency Overhaul",
    situation: "Multi-cluster enterprise Snowflake warehouse costs escalated past $450k annually due to unoptimized queries and auto-suspend timeouts.",
    task: "Optimize warehouse clustering, rewrite expensive subqueries, and implement auto-scaling policies.",
    action: "Partitioned heavy analytical tables with clustering keys, restructured incremental dbt models, and tuned query cache utilization.",
    result: "Reduced monthly compute expenditure by $140,000/yr (32% savings) while improving P95 dashboard query latency from 8.2s to 1.4s.",
    quantifiable_metrics: "$140k/yr cost reduction, 8.2s -> 1.4s P95 query speedup",
    created_at: new Date().toISOString(),
  },
  {
    id: "ev-2",
    competency: "dbt Dimensional Modeling & CI/CD",
    category: "DATA_ENGINEERING",
    skill_or_tool: "dbt",
    proficiency_level: "EXPERT",
    verified: true,
    employer: "Acme Corp",
    project_title: "Core Data Mart Standardization & CI Testing Pipeline",
    situation: "Disorganized raw schemas caused duplicated reporting logic and conflicting revenue metrics across departments.",
    task: "Architect unified Kimbal-style dimensional mart with automated schema tests and documentation.",
    action: "Built 80+ modular dbt models, configured generic/singular tests, and implemented Slim CI in GitHub Actions.",
    result: "Eliminated metric divergence across finance and product teams; reduced ETL build failure rate from 14% to 0.4%.",
    quantifiable_metrics: "80+ models, 0.4% ETL failure rate, 100% metric consistency",
    created_at: new Date().toISOString(),
  },
  {
    id: "ev-3",
    competency: "Looker & Semantic Layer Architecture",
    category: "BUSINESS_INTELLIGENCE",
    skill_or_tool: "Looker",
    proficiency_level: "EXPERT",
    verified: true,
    employer: "Acme Corp",
    project_title: "Executive Revenue & Cohort Analytics Semantic Layer",
    situation: "Executive team lacked self-serve cohort retention analytics, requiring ad-hoc SQL pulls from data engineers.",
    task: "Build scalable LookML semantic models with user-defined aggregates and caching.",
    action: "Modeled LookML explores, built liquid parameters for dynamic filtering, and scheduled automated PDT builds.",
    result: "Enabled 120+ non-technical business stakeholders to self-serve 85% of analytical queries without data team intervention.",
    quantifiable_metrics: "120+ self-serve users, 85% self-service rate",
    created_at: new Date().toISOString(),
  },
  {
    id: "ev-4",
    competency: "SQL & Query Performance Tuning",
    category: "DATA_ENGINEERING",
    skill_or_tool: "SQL",
    proficiency_level: "EXPERT",
    verified: true,
    employer: "Acme Corp",
    project_title: "Real-time Attribution & Window Aggregations",
    situation: "Daily attribution models ran for 4.5 hours, delaying daily operational morning standups.",
    task: "Refactor window functions, push down predicates, and eliminate Cartesian joins.",
    action: "Re-engineered SQL logic using QUALIFY clauses and partitioned CTEs.",
    result: "Reduced batch runtime from 4.5h to 38 minutes (86% runtime reduction).",
    quantifiable_metrics: "86% runtime reduction (4.5h -> 38m)",
    created_at: new Date().toISOString(),
  },
];

export const FALLBACK_RECRUITERS: Recruiter[] = [
  {
    id: "rec-1",
    name: "Sarah Jenkins",
    company_name: "Snowflake",
    role: "Lead Technical Recruiter",
    email: "sjenkins@snowflake.example.com",
    linkedin_url: "https://linkedin.com/in/sarahjenkins-demo",
    relationship_status: "ACTIVE",
    hiring_authority_tier: "PRIMARY_RECRUITER",
    notes: "Direct sourcer for Core Data & Analytics Engineering team.",
    created_at: new Date().toISOString(),
  },
  {
    id: "rec-2",
    name: "Alex Rivera",
    company_name: "Stripe",
    role: "Senior Sourcer — Infrastructure",
    email: "arivera@stripe.example.com",
    linkedin_url: "https://linkedin.com/in/alexrivera-demo",
    relationship_status: "CONTACTED",
    hiring_authority_tier: "TECHNICAL_SOURCER",
    notes: "Connected on LinkedIn regarding BI Solutions Architect headcount.",
    created_at: new Date().toISOString(),
  },
];

export const FALLBACK_APPLICATIONS: Application[] = [
  {
    id: "app-1",
    job_id: "demo-snow-1",
    stage: "APPLIED",
    created_at: new Date().toISOString(),
    notes: "Submitted tailored resume highlighting warehouse cost optimization.",
  },
  {
    id: "app-2",
    job_id: "demo-stripe-2",
    stage: "RECRUITER_SCREEN",
    created_at: new Date().toISOString(),
    notes: "Screen scheduled for Thursday 2:00 PM PST.",
  },
];

export const FALLBACK_APPROVALS: ApprovalRequest[] = [
  {
    id: "appr-1",
    title: "Cold Recruiter Outreach to Stripe",
    request_type: "OUTREACH_EMAIL",
    action_type: "DISPATCH_RECRUITER_OUTREACH",
    summary: "Cold recruiter outreach email to Alex Rivera citing verified Snowflake & LookML dimensional modeling impact.",
    reason: "High strategic fit with documented enterprise dimensional modeling evidence.",
    status: "PENDING",
    proposed_content: {
      recipient: "arivera@stripe.example.com",
      subject: "Lead BI Solutions Architect — Senior Data Engineer Candidate Background",
      body: "Hi Alex,\n\nI noticed Stripe's opening for the Lead BI Solutions Architect role. Over the past 4 years, I've architected enterprise dbt/Snowflake dimensional marts that cut query latency by 82% and supported 120+ self-serve Looker users.\n\nGiven Stripe's focus on low-latency data infrastructure, I'd love to connect for 10 minutes.\n\nBest,\nKavish",
    },
    created_at: new Date().toISOString(),
  },
];

export const FALLBACK_SCORING_CONFIG: ScoringConfig = {
  id: "cfg-1",
  config_name: "Default Senior BI Policy",
  weight_skill_fit: 0.35,
  weight_seniority: 0.15,
  weight_domain: 0.15,
  weight_compensation: 0.25,
  weight_freshness: 0.05,
  weight_hiring_signal: 0.05,
  weight_recruiter: 0.0,
  is_active: true,
};

export const FALLBACK_INTEGRATIONS: IntegrationsStatus = {
  database: {
    engine: "PostgreSQL / SQLite WAL",
    url_configured: true,
    status: "HEALTHY",
  },
  google_sheets: {
    configured: false,
    spreadsheet_id: "optional-control-surface",
    status: "STANDBY",
  },
  ai_provider: {
    provider: "Deterministic Matcher + Local LLM",
    configured: true,
    status: "ONLINE",
  },
  email_smtp: {
    configured: false,
    host: "Level 2 Gate Active",
    status: "GATE_ENFORCED",
  },
};
